name: Pre-commit Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: cx-public-ubuntu-x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Check Python version
        run: python --version

      - name: Install pre-commit from Echo registry
        run: |
          pip install pre-commit==4.6.0 --index-url https://:${{ secrets.ECHO_ACCESS_KEY }}pypi.echohq.com/simple

      - name: Verify pre-commit installation
        run: pre-commit --version
